version: '3'

services:

  node:
    build:
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["node", "index.js"]
    networks:
      - node-network
    ports:
      - 3000:3000
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network      

networks:
  node-network:
    driver: bridge
